rails_projects/miam/config/routes.rb
Rails.application.routes.draw do
  #root :to => "establishments#index"
  get '/' => 'home#index'

  
  resources :users do
    member do
      put 'starts_following'
    end
  end
  
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
  
  resources :establishments do
    member do
      put 'visited_this_place'
    end
    resources :reviews, :except => [:show, :index]
    
    
  end
 
  
  resources :owners
  
  resources :cities do
    collection do
      get 'search_cities'
    end
  
  end
end

rails_projects/miam/app/models/establishment.rb
class Establishment < ActiveRecord::Base
  belongs_to :city
  has_many :reviews
  has_many :visits
  has_many :users, :through => :visits
  
  has_attached_file :logo, :styles => { :medium => "300x300>", :small => "150x150>", :exsmall => "50x50>" }, :url  => "/assets/users/:id/:style/:basename.:extension", :path => ":rails_root/public/assets/users/:id/:style/:basename.:extension"
  validates_attachment_content_type :logo, :content_type => ['image/jpeg', 'image/png']
  
  def score
    total_score = 0
    counter = 0
    self.reviews.each do |review|
      total_score = total_score + review.rate
      counter = counter + 1
    end
    if total_score != 0 and counter != 00
      score_to_return = total_score / counter
    else
      score_to_return = nil
    end
    score_to_return
  end
  
  def has_been_visited_by(follower)
    result = false
    if self.users.include?(follower).!()
      self.users.push(follower)
      result = true
    end
    result
  end
end

rails_projects/miam/app/controllers/establishments_controller.rb
class EstablishmentsController < ApplicationController
  def index
    #require_relative 'citiesdb'
    @establishments = Establishment.all
    @userr = User.find(16)
    render :index
    
  end
  
  def new
    @establishment = Establishment.new
    @city = City.new
    render :new
  end
  
  def create
    @establishment = Establishment.new(params[:establishment])
    @city = City.create(params[:city])
    @establishment.city = @city
    
    if @establishment.save()
      puts "should create an alert to inform user."
      redirect_to new_establishment_path
    else
      render :new
    end
  end
  
  def visited_this_place
    @place_visited = Establishment.find(params[:id])
    @visitor = User.find(1)
    if @place_visited.has_been_visited_by @visitor
      redirect_to establishment_path(@place_visited)
    else
      render :notok
    end
  end
  
  def show
    @establishment = Establishment.find(params[:id])
    @review = Review.new
    render :show
  end
  private
  def establishment_params
    params.require(:establishment).permit(:name, :description, :adress, :city, :logo)
  end
end

rails_projects/miam/app/views/establishments/_form.html.erb
<%= render "layouts/errors", :object => @establishment %>
<div class="container">
<div class="col-md-6 center form-style">
<%= form_for @establishment do |f| %>
  <div class="form-group">
  
    <%= f.text_field :name, class:"form-control input-style",:placeholder => "Nom du restaurant" %>
</div>
  <div class="form-group">
 
    <%= f.text_field :adress, class:"form-control input-style",:placeholder => "Adresse du restaurant" %>
  </div>
  <div class="form-group">
    <%= fields_for :city, @establishment.city, remote: true do |city_fields| %>
    <div class="form-group">

      <%= city_fields.text_field :name, class:"form-control input-style ajax-search-city",:placeholder => "Où se trouve t'il? (commune)" %>
      <div class="found-cities"><span>why?</span></div>
  </div>
    <div class="form-group">
  <label for="choix_bieres">Indiquez votre bière préférée :</label>
    <input list="bieres" type="text" id="choix_bieres" class="form-control input-style">
    <datalist id="bieres" class="input-style">
      <option value="Meteor">
      <option value="Pils">
      <option value="Kronenbourg">
      <option value="Grimbergen">
    </datalist>

  <% end %>
 
    <%= f.text_area :description, class:"form-control input-style",:placeholder => "Quel est la description?" %>
  </div>
  <div class="form-group">
   <span class="glyphicon glyphicon-cloud-upload" aria-hidden="true"> <%= f.label :logo %> (conseillé): <%= f.file_field :logo %></span>
   
    </div>

  <%= f.submit class: 'button-to-sign' %>
  
<% end %>
</div>
  </div>
</div>

rails_projects/miam/app/views/establishments/index.html.erb
<div class="container">
  

      <div class="row">
        <h1 class="title">Où se goinfrer?</h1>
      <br>
        <% @establishments.each do |establishment| %>
          
          
               
              <div class=" col-sm-12 col-md-3">
<div class="panel panel-default ">
  <div class="panel-heading panel-heading-burger">
                      <h3 class="center title-burger-panel"><%= link_to establishment.name, establishment_path(establishment) %></h3>

  </div>
  <div class="panel-body ">
    <%= image_tag establishment.logo.url(:medium), :class => "img-responsive" %>
   
      <br>
                  <% if establishment.score.nil?.!() %>
                    <div class="progress">
                      <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: <%= establishment.score*10 %>%">
                        <span class="sr-only">40% Complete (success)</span>
                      </div>
                    </div>
                  <% else %>
                  <%= link_to "Soyez le premier à mettre une note!", establishment_path(establishment) %>
                  <% end %>
                  <table class="table ">
                    
                    <tr>
                      <td><span class=' glyphicon glyphicon-home' aria-hidden='true'></span></td>
                      <td>
                        <%= establishment.adress %>
                        <br>
                      
                      </td>
                    </tr>
                    <tr>
                      
                      <td><span class='glyphicon glyphicon-heart' aria-hidden='true'></span></td>
                      <td><%= establishment.users.length %> lovers</td>
                    </tr>
                  </table>
                  <p><%= truncate(establishment.description, :length => 50) %></p><%= link_to "=> " + establishment.name, establishment_path(establishment) , class: "btn btn-warning pull-right", role: "button" %>
  </div>
</div>
              </div>
            
                   
        <% end %>
      </div> 
      <h2>You're a restaurant owner? Does your establishment serve tasty burgers on a regular basis? Register it right now!</h2>
      <%= link_to "Register my restaurant", new_establishment_path %>
</div>

rails_projects/miam/app/views/establishments/new.html.erb
<h1 class="title">Ajouter un restaurant</h1>
<hr size="30px" width="50%"  align=center>
<%= render 'form' %>

rails_projects/miam/app/views/establishments/notok.html.erb
pas bon

rails_projects/miam/app/views/establishments/show.html.erb
<div class="jumbotron col-md-6 clear-fix">
  <%= image_tag @establishment.logo.url(:medium), :class => "img-responsive" %>

  <h3><%= @establishment.name %></h3>
  Note moyenne: <%= @establishment.score %>
</div>



<% if @establishment.reviews.any? %>
  <h4>Reviews: </h4>
  <ul>
    <% @establishment.reviews.each do |review| %>
      <li>
        <%= link_to review.user.username, user_path(review.user) %> | 
        Rating: <%= review.rate %>/10
        <p><%= review.text %></p>
      </li>
    <% end %>
  </ul>
<!-- Create in jquery a rolldown form allowing to insert a review when user visited the restaurant -->

<% end %>
<%= link_to "I visited this place ", visited_this_place_establishment_path(@establishment), :data => { :method => "put"} %>
<h4>Already been there ?</h4>
<%= form_for [@establishment,@review] do |f| %>
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: 'form-control', :html => {:row => "8"} %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :rate %>
    <%= f.number_field :rate, class: 'form-control', max: "10" %>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>  
<% end %>