rails_projects/miam/config/routes.rb
Rails.application.routes.draw do
  #root :to => "establishments#index"
  get '/' => 'home#index'

  
  resources :users do
    member do
      put 'starts_following'
    end
  end
  
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
  
  resources :establishments do
    member do
      put 'visited_this_place'
    end
    resources :reviews, :except => [:show, :index]
    
    
  end
 
  
  resources :owners
  
  resources :cities do
    collection do
      get 'search_cities'
    end
  
  end
end

rails_projects/miam/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password

  
  has_many :reviews
  has_many :user_followings, :foreign_key => :user_a_id, :dependent => :destroy
  has_many(:reverse_user_followings, :class_name => :UserFollowing,
      :foreign_key => :user_b_id, :dependent => :destroy)  
  has_many :users, :through => :user_followings, :source => :user_b
  has_many :visits
  has_many :establishments, :through => :visits
  
  has_attached_file :avatar,:styles => { :small => "150x150>", :exsmall => "50x50>" }, :url  => "/assets/users/:id/:style/:basename.:extension", :path => ":rails_root/public/assets/users/:id/:style/:basename.:extension"
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']
  
  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end
  def self.authenticate(email, password)
  end
  
  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def is_a_follower?(other_user)
    self.users.include?(other_user)
  end
  def starts_to_be_followed_by(follower)
    result = false
    if self.users.include?(follower).!()
      self.users.push(follower)
      result = true
    end
    result
  end
  
end

rails_projects/miam/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new()
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.signup_confirmation(@user).deliver

      flash[:notice] = "Welcome to the site!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end
  
  def show
    @user = User.find(params[:id])
    render :show
  end
  
  def starts_following
    @user_to_be_followed = User.find(params[:id])
    @follower = User.find(3)
    if @user_to_be_followed.starts_to_be_followed_by @follower
      @user_to_be_followed.users.push(@follower)
      redirect_to user_path(@user_to_be_followed)
    else
      render :notok
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :username, :email, :password, :password_confirmation, :avatar)
  end
end

rails_projects/miam/app/views/users/new.html.erb
<h1 class="title">Inscription</h1>
<hr size="30px" width="50%"  align=center>

<%= render "layouts/errors", :object => @user %>

<div class="container">
<div class="col-md-6 center form-style">
  <%= form_for @user, :html => { :multipart => true } do |f| %>
  <div class="form-group">
  
    <%= f.text_field :firstname, class:"form-control input-style",:placeholder => "Quel est votre prénom" %>
</div>
  <div class="form-group">
    <%= f.text_field :lastname, class:"form-control input-style",:placeholder => "Et votre nom alors?" %>
</div>
  <div class="form-group">
    <%= f.text_field :username, class:"form-control input-style",:placeholder => "Sous quel pseudonyme souhaitez-vous être vu?" %>
</div>
  <div class="form-group">
  
    <%= f.text_field :email, class:"form-control input-style",:placeholder => "Email" %>
</div>
  <div class="form-group">
 
    <%= f.text_field :password, class:"form-control input-style",:placeholder => "Votre mot de passe?" %>
  </div>
  <div class="form-group">
 
    <%= f.password_field :password_confirmation, class:"form-control input-style ",:placeholder => "Retapez votre mot de passe s'il vous plait" %>
  </div>
  
  <div class="form-group">
    <%= f.file_field :avatar %>
  </div>
  
    

  <div class="form-group">
  <%= f.submit class: 'button-to-sign ' %>
  </div>
  
<% end %>
</div>
  </div>

rails_projects/miam/app/views/users/notok.html.erb
<h1>NOT OK</h1>

rails_projects/miam/app/views/users/show.html.erb
<h3><%= @user.username %></h3>
<br>
has <%= @user.users.length %> followers
<br>
has been to <%= @user.establishments.length %> restaurants
<%= link_to "Suivre", starts_following_user_path(@user), :data => {:method => "put"} %>