rails_projects/wildfire/to_do/config/routes.rb
Rails.application.routes.draw do
  root :to => "lists#index"
  
  resources :lists do
    resources :tasks, :except => [:show, :index] do
      member do
        patch 'done_true'
      end
      member do
        patch 'done_false'
      end
      
    end
  end
end

rails_projects/wildfire/to_do/app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  
  validates :name, :presence => true
  validates :description, :presence => true
  
  
end

rails_projects/wildfire/to_do/app/models/task.rb
class Task < ActiveRecord::Base 
  belongs_to :list
  validates :description, :presence => true
  
  scope(:not_done, -> do
    where({:done => false})
  end)

  scope(:done, -> do
    where({:done => true})
  end)
end

rails_projects/wildfire/to_do/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails_projects/wildfire/to_do/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    render :index
  end
  
  def show
    @list = List.find(params[:id])
    render :show
  end
  
  def new
    @list = List.new 
    render :new
  end
  
  def create
    @list = List.new params[:list]
    
    if @list.save
      flash[:notice] = "List successfully added!"
      redirect_to lists_path
    else
      flash[:alert] = "there were some problem!"
      render :new
    end
  end
  
  def edit
    @list = List.find(params[:id])
    render :edit
  end
  
  def update
    @list = List.find params[:id]
    
    if @list.update(params[:list])
      redirect_to lists_path
    else
      render :edit
    end
  end
  
  def destroy
    @list = List.find params[:id]
    @list.destroy
    
    redirect_to lists_path
  end
end

rails_projects/wildfire/to_do/app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
end

rails_projects/wildfire/to_do/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @task = @list.tasks.new
  end
  
  def create
    
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(params[:task])
    @task.done = false
    if @task.save
      flash[:notice] = "Your task has been successfully added"
      redirect_to list_path(@task.list)
      
    else
      flash[:alert] = "there were some problems while we tried to process the creation of your task .."
      render :new
    end
  end
  
  def edit
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    render :edit
  end
  
  def update
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    
    if @task.update(params[:task])
      flash[:notice] = "Your task has been successfully edited"
      redirect_to list_path(@task.list)
    else
      render :edit
    end
  end
  
  def destroy
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    if @task.destroy
      flash[:notice] = "Your task has been successfully deleted"
    else
      flash[:alert] = "there were some problems while we tried to delete your task .."
    end
    redirect_to list_path(@task.list)

  end
  
  def done_true
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    Task.update(params[:id], :done => true)
    redirect_to list_path(@task.list)
  end
  
  def done_false
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    Task.update(params[:id], :done => false)
    redirect_to list_path(@task.list)
  end
end

rails_projects/wildfire/to_do/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_projects/wildfire/to_do/app/helpers/puppies_helper.rb
module PuppiesHelper
end

rails_projects/wildfire/to_do/app/views/lists/_form.html.erb
<%= render "layouts/errors", :object => @list %>

<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

rails_projects/wildfire/to_do/app/views/lists/_individual_task.html.erb
<li>
  <%= object.description %> |
  <%= link_to "Edit", edit_list_task_path(@list, object) %> |
  <%= link_to "Delete", list_task_path(@list, object), :data => { :confirm => "you sure?", :method => "delete"} %> |
  <% if done %>
    <%= link_to "Mark as not done", done_false_list_task_path(@list, object), :data => { :method =>"patch" } %>
  <% else %>
    <%= link_to "Mark as done", done_true_list_task_path(@list, object), :data => { :method =>"patch"}%>
  <% end %>
</li>

rails_projects/wildfire/to_do/app/views/lists/edit.html.erb
<h1>Edit list</h1>

<%= render 'form' %>

rails_projects/wildfire/to_do/app/views/lists/index.html.erb
<h1>Lists</h1>

<ul>
  <% @lists.each do |list| %>
  <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<%= link_to "create a new list", new_list_path %>

rails_projects/wildfire/to_do/app/views/lists/new.html.erb
<h1>New list</h1>


<%= render 'form' %>

rails_projects/wildfire/to_do/app/views/lists/show.html.erb
<% content_for(:title, "List | Ca Ca") %>

<h1><%= @list.name %></h1>

<h4><%= @list.description %> <%= link_to "edit", edit_list_path(@list) %></h4>
<p><%= link_to "Delete", list_path(@list), :data => { :confirm => "are you sure?",
  :method => "delete"} %></p>

<% if @list.tasks.any?() %>
  <h4>Here are the tasks for this list:</h4>
  <h6>Not done:</h6>
  <ul>
    <% @list.tasks.not_done.each do |task| %>
      <%= render 'individual_task', {:object => task, :done => false} %>    
    <% end %>
  </ul>
  <h6>Done:</h6>
  <ul>
    <% @list.tasks.done.each do |task| %>
      <%= render 'individual_task', :object => task, :done => true %>   
    <% end %>
  </ul>
<% else %>
  <p>There are no tasks yet...</p>
<% end %>

<%= link_to "Add a task", new_list_task_path(@list) %>


<p><%= link_to "Return to lists", lists_path %></p>