rails_projects/miam/config/routes.rb
Rails.application.routes.draw do
  #root :to => "establishments#index"
  get '/' => 'home#index'

  
  resources :users do
    member do
      put 'starts_following'
    end
  end
  
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
  
  resources :establishments do
    member do
      put 'visited_this_place'
    end
    resources :reviews, :except => [:show, :index]
    
    
  end
 
  
  resources :owners
  
  resources :cities do
    collection do
      get 'search_cities'
    end
  
  end
end

rails_projects/miam/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Miam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid ">
  <!--<nav class="navbar col-md-12">
        <div class="container-fluid">
              

         
          <div class="pull-right">
           <button type="button" class="btn btn-default navbar-btn " data-toggle="modal" data-target="#myModal">Se connecter</button>

            <%= link_to raw("<span class=' glyphicon glyphicon-user' aria-hidden='true'></span> Se connecter"), "#", class: 'button-to-sign' %>
            <%= link_to raw("<span class=' glyphicon glyphicon-pencil' aria-hidden='true'></span> S'inscire"), new_user_path, class: 'button-to-sign' %>
          </div>
        </div>
    </nav>-->
  <div class="row">
    <div class="col-md-2 left-menu">
      <a href="/">
      <img class="img-responsive logo" src="http://img11.hostingpics.net/thumbs/mini_142853mistertasttyy.png" alt="Logo" /></a>
      <ul class="menu">
        <li>Accueil</li>
        <li>Burgers</li>
        <li>Vos restaurants</li>
        <li>A propos</li>  
      </ul>
      
      <p class="center">on a tous un gros lard qui sommeille au plus profond de nous...</p>
    </div>
  <div class="col-md-10 main-right-side">
    <nav class="navbar ">
        <div class="container-fluid">
              

          <!--<form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text " class="form-control burger-search" placeholder="Rechercher un restaurant">
            </div>
            <button type="submit" class="btn btn-default">Lancer</button>
          </form>-->
          <%= link_to raw("<button type='button' class='btn button-to-sign button-register-restaurant '><span class=' glyphicon glyphicon-home' aria-hidden='true' ></span> Ajouter un restaurant</button>"),  new_establishment_path %>
          <div class="pull-right">
            
            
            <% if current_user %>
              <span>connecté en tant que <%= current_user.username %></span>
                <%= link_to raw("<button type='button' class='btn button-to-sign'><span class=' glyphicon glyphicon-pencil' aria-hidden='true' ></span> Déconnexion</button>"), log_out_path %>
            <%= image_tag current_user.avatar.url(:exsmall), :class => "img-circle" %>
            &nbsp;
             <span class="glyphicon glyphicon-wrench" aria-hidden="true"> </span>
            <% else %>
              <button type="button" class="btn button-to-sign" data-toggle="modal" data-target="#myModal"><span class=' glyphicon glyphicon-user' aria-hidden='true'></span> Se connecter</button>
           
            
            <%= link_to raw("<button type='button' class='btn button-to-sign'><span class=' glyphicon glyphicon-pencil' aria-hidden='true' ></span> S'inscire</button>"), new_user_path %>
            <% end %>
           
          </div>
        </div>
    </nav> 

    <%= yield %>
    
      <div class="modal fade " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <img class="img-responsive logo-connexion" src="http://img11.hostingpics.net/thumbs/mini_194399mistertasttyysanstexte.png" alt="Heberger image" />   
        <div class="modal-dialog modal-sm">
              <div class="modal-content">
                <div class="modal-header"  >
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title background-to-orange" id="myModalLabel">Connexion</h4>
                </div>
                <div class="modal-body">
                  <div class="container-fluid">
                   
            <%=form_tag log_in_path do%>
 

                      <div class="form-group">
                        <%=label_tag :email %>
<%=text_field_tag :email, nil,class: 'form-control' %>
                      </div>
                      <div class="form-group">
<%=label_tag :password %>
<%=password_field_tag :password, nil,class: 'form-control' %>
                      </div>

                  </div>
                </div>
                <div class="modal-footer">
                  <%=submit_tag "Connectez-vous", class: 'btn btn-success' %>
                </div>
                <% end %>        
                    
                    
              </div>
            </div>
          </div> 
    
    
    
    
    </div>
  </div>
</div>
</body>
</html>